export enum RoutesEnum {
  HOME = 'Home',
  PROFILE = 'Profile',
  SETTINGS = 'Settings',
  PROFILE_SETTINGS_SCREEN = 'ProfileSettingsScreen',
  DASHBOARD_SCREEN = 'DashboardScreen',
  GET_STARTED_SCREEN = 'GetStartedScreen',
  ONBOARDING_SCREEN = 'OnboardingScreen',
  LOGIN_SCREEN = 'LoginScreen',
  PASSWORD_RESET_SCREEN = 'PasswordResetScreen',
  FORGOT_PASSWORD_SCREEN = 'ForgotPasswordScreen',
  REGISTER_SCREEN = 'RegisterScreen',
  VERIFY_ACCOUNT_SCREEN = 'VerifyAccountScreen',
  NOTIFICATION_SCREEN = 'NotificationScreen',
  MENU_SCREEN = 'MenuScreen',
  VISITORS_SCREEN = 'VisitorsScreen',
  SHOP_NOW_SCREEN = 'ShopNowScreen',
  FEES_SCREEN = 'FeesScreen',
  ORDERS_SCREEN = 'OrdersScreen',
  EMERGENCIES_SCREEN = 'EmergenciesScreen',
  MY_STORES_SCREEN = 'MyStoresScreen',
  SUBSCRIPTION_SCREEN = 'SubscriptionScreen',
}

export enum StacksEnum {
  AUTH_STACK = 'AUTH_STACK',
  APP_STACK = 'APP_STACK',
  DASHBOARD_STACK = 'DASHBOARD_STACK',
  MENU_STACK = 'MENU_STACK',
  ORDERS_STACK = 'ORDERS_STACK',
  VISITORS_STACK = 'VISITORS_STACK',
  SHOP_NOW_STACK = 'SHOP_NOW_STACK',
  FEES_STACK = 'FEES_STACK',
  EMERGENCIES_STACK = 'EMERGENCIES_STACK',
  MY_STORES_STACK = 'MY_STORES_STACK',
  NOTIFICATION_STACK = 'NOTIFICATION_STACK',
  SUBSCRIPTION_STACK = 'SUBSCRIPTION_STACK',
}
